---
parser: babel-eslint

extends: airbnb

plugins:
  - react
  - import

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true

env:
  browser: true
  node: true
  mocha: true

settings:
  import/extensions: [.js, .jsx]

rules:
# Variables
  no-undef: 2
  no-unused-vars: [2, { vars: all, args: none }]

# Stylistic issues
  indent: [1, 2, { SwitchCase: 1, VariableDeclarator: 2 }]
  id-length: [1, { min: 2, exceptions: [_, e, i, k, v] }]
  space-before-function-paren: [1, never]
  no-underscore-dangle: 0

  comma-dangle: [2, never]
  key-spacing: [2, {beforeColon: false, afterColon: true, mode: minimum}]
  max-len: [2, 120]
  no-param-reassign: 0
  one-var: 0

# Imports
  import/no-unresolved: 0
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/extensions: 0
  import/newline-after-import: 2
  import/prefer-default-export: 2
  import/no-named-as-default: 1
  import/no-named-as-default-member: 1
  import/no-duplicates: 1

# React
  jsx-quotes: [2, prefer-double]
  react/jsx-curly-spacing: [2, never]
  react/jsx-no-duplicate-props: [2, { ignoreCase: true }]
  react/jsx-no-undef: 2
  react/jsx-sort-prop-types: 0
  react/jsx-sort-props: 0
  react/no-did-mount-set-state: 1
  react/no-did-update-set-state: 0
  react/no-multi-comp: [2, { ignoreStateless: true }]
  react/no-unknown-property: 2
  react/prop-types: 2
  react/react-in-jsx-scope: 2
  react/require-extension: [1, { extensions: [.js, .jsx] }]
  react/self-closing-comp: 2
  react/wrap-multilines: 2
  react/jsx-closing-bracket-location: [2, after-props]
  react/jsx-indent-props: 0
  react/jsx-first-prop-new-line: 0
  react/sort-comp:
    - warn
    - { order: [statics, static-methods, lifecycle, /^(on|handle).+$/, everything-else, render, /^_.+$/] }
