sudo: required
language: ruby

services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_2862f5971073_key -iv $encrypted_2862f5971073_iv
    -in client_secrets.json.enc -out client_secrets.json -d
  - openssl enc -d -aes-256-cbc -k $ENV_CRYPT_KEY -in .env.enc -out .env
install:
  - docker build -t confy:1.1 .
before_script:
  - docker-compose run web bundle exec rake db:create
  - docker-compose run web bundle exec rake db:migrate
script:
  - docker-compose run web bundle exec rake test:all
addons:
  code_climate:
    repo_token: a28eb2810b0b0acd8376c2cf2b1c4aea8736e1c6854bada55fd73b740dd6261d
