version: '3'
services:
  web:
    image: confy:1.1
    command: rails s -b 0.0.0.0
    environment:
        REACT_ON_RAILS_ENV: HOT
        PORT: 3000
        PRY: 'true'
        REDIS_PROVIDER: REDIS_URL
        REDIS_URL: 'redis://redis:6379'
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/srv/www/web
    depends_on:
      - db
      - redis
      - sidekiq
  sidekiq:
    image: confy:1.1
    command: sidekiq -q default
    environment:
        REDIS_PROVIDER: REDIS_URL
        REDIS_URL: 'redis://redis:6379'
    depends_on:
      - db
      - redis
  dev-server:
    image: confy:1.1
    command: npm run server:dev
    ports:
      - 3500:3500
    environment:
      HOT_RAILS_PORT: 3500
  db:
    image: postgres:9.6
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
  redis:
    image: redis:3.2
volumes:
  dbdata:
