apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: confy-u2i-com-tls
  namespace: confy
spec:
  secretName: confy-u2i-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: confy.u2i.com
  renewBefore: 720h # 30 days
  dnsNames:
    - confy.u2i.com

