apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: confy-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "confy-ip"
spec:
  backend:
    serviceName: web-service
    servicePort: 80
  tls:
  - secretName: confy-u2i-com-tls
    hosts:
    - confy.u2i.com
