apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'confy@u2i.com'
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      -
        http01:
          ingress:
            name: confy-ingress
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'confy@u2i.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      -
        http01:
          ingress:
            name: confy-ingress

